name: Generate Subscriptions

on:
  workflow_dispatch:
    inputs:
      input_data_b64:
        description: 'Base64 encoded sub links'
        required: true
      custom_name:
        description: 'Custom server name'
        required: false
        default: 'ArsenVPN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Processing Script
        env:
          INPUT_DATA_B64: ${{ github.event.inputs.input_data_b64 }}
          CUSTOM_NAME: ${{ github.event.inputs.custom_name }}
        run: python process.py

      - name: Commit and Push Sub File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sub.txt
          git commit -m "Update subscription list" || exit 0
          git push
